version: "3.7"

services:
  db:
    image: mysql:latest
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default

networks:
    default:
        external:
            name: docker_default